# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
gems: [jekyll-paginate]

# Setup
title:            Zhiyu Xu
tagline:          'A Jekyll theme'
description:      'Welcome to my personal website!'
url:              https://toby-x.github.io
baseurl:          /

author:
  name:           'Zhiyu Xu'
  url:            https://toby-x.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
